compile1:
	javac BpTreeMap.java

compile2:
	javac ExtHashMap.java

compile3:
	javac LinHashMap.java

javadoc:
	javadoc BpTreeMap.java LinHashMap.java ExtHashMap.java

clean:
	rm -f *.class

run1:
	java BpTreeMap.java 9

run2:
	java ExtHashMap.java

run3:
	java LinHashMap.java
